version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: webserver-sample-server
    container_name: webserver-sample-server
    ports:
      - "3000:3000"
    volumes:
      - ./server/:/app:delegateds
    tty: true
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: admin-pass
      DB_NAME: postgres_db
      DB_PORT: 5432
  
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: webserver-sample-front
    container_name: webserver-sample-front
    ports:
      - "3001:3000"
    volumes:
      - ./front/:/app:delegateds
    tty: true

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: webserver-sample-db
    container_name: webserver-sample-db
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin-pass
