version: '3'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./front/:/app:delegateds
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "3001:5555"
    volumes:
      - ./server/:/app:delegateds
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - ./mysql/data:/var/lib/mysql
